### ISSUE TITLE
[Concept] Inclusion from the Streets mod

### ISSUE THREAD

**Issue by ChandlerBing1994** [The-Architect-Crew/the-architect-game#67]
Keep:
-Concrete (but retexture it to make it 16bit like the rest)
-Asphalt
-Asphalt with dashed line
-Advanced manhole
-Street lamp
-Concrete wall (the one with the base, not the completely flat one)

Extras to keep:
-All the yellow road markings

Trash:
Everything else.

**Comment by wrynvera** [comment]
Agree with the current inclusion.
I like to see an expansion of modern street/road decorations however.
I am aware that streets 2.0 provides additional decoration, but it is done in poor taste IMHO.

To compare, simply look at this Minecraft mod that does streets; https://www.curseforge.com/minecraft/mc-mods/furenikusroads
It isn't that hard to achieve that as well.

But as a basis, im ok with keeping the listed nodes above for now.

**Comment by bobmacphee** [comment]
I agree that we don't need all of the streets mod but I do think we should keep road markings such as parking signs, these can add a lot to a build, and also the concrete barrier things (Not sure if that's part of this mod or not).

**Comment by ChandlerBing1994** [comment]
Added the concrete barriers. Forgot.

**Comment by bobmacphee** [comment]
> Added the concrete barriers. Forgot.

In that case, if we can keep the basic road markings, I'm in.

**Comment by ChandlerBing1994** [comment]
I'm fine with the yellow road markings as well.

**Comment by lisacvuk** [comment]
Concrete + Asphalt (w markings) + Barriers looks good to me +1

**Comment by lumberjackgames** [comment]
Looks good :+1:

**Comment by wrynvera** [comment]
#79

**Comment by wrynvera** [comment]
Issue discussion transferred to discord for consistency
